### ISSUE TITLE
Images on social media don't look good.

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/thinkshout#222]
Facebook and Twitter pull the Captcha image when sharing posts. Here's an example of tags from David Walsh's blog that should help us improve this. View Source of this ticket if you need to see the tags.
```
<link rel="canonical" href="http://davidwalsh.name/twitter-cards" />
<meta property="og:title" content="How to Create a Twitter Card" />
<meta property="og:type" content="article" />
<meta property="og:url" content="http://davidwalsh.name/twitter-cards" />
<meta property="og:image" content="http://davidwalsh.name/wp-content/themes/punky/images/logo.png" />
<meta property="og:site_name" content="David Walsh Blog" />
<meta property="fb:admins" content="211704301" />
<meta property="og:description" content="Twitter&#039;s new Twitter Cards API allows developers to add META tags to their website, and Twitter will build card content from links to a given site." />
<meta property="article:published_time" content="2012-12-10T10:19:47Z" />
<meta property="article:modified_time" content="2015-05-18T08:39:08Z" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@davidwalshblog" />
<meta name="twitter:domain" content="http://davidwalsh.name" />
<meta name="twitter:description" content="Twitter&#039;s new Twitter Cards API allows developers to add META tags to their website, and Twitter will build card content from links to a given site." />
<meta itemprop="image" content="http://davidwalsh.name/wp-content/themes/punky/images/logo.png" />
```

**Comment by Greg-Boggs** [comment]
<link rel="canonical" href="http://davidwalsh.name/twitter-cards" />
<meta property="og:title" content="How to Create a Twitter Card" />
<meta property="og:type" content="article" />
<meta property="og:url" content="http://davidwalsh.name/twitter-cards" />
<meta property="og:image" content="http://davidwalsh.name/wp-content/themes/punky/images/logo.png" />
<meta property="og:site_name" content="David Walsh Blog" />
<meta property="fb:admins" content="211704301" />
<meta property="og:description" content="Twitter&#039;s new Twitter Cards API allows developers to add META tags to their website, and Twitter will build card content from links to a given site." />
<meta property="article:published_time" content="2012-12-10T10:19:47Z" />
<meta property="article:modified_time" content="2015-05-18T08:39:08Z" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@davidwalshblog" />
<meta name="twitter:domain" content="http://davidwalsh.name" />
<meta name="twitter:description" content="Twitter&#039;s new Twitter Cards API allows developers to add META tags to their website, and Twitter will build card content from links to a given site." />
<meta itemprop="image" content="http://davidwalsh.name/wp-content/themes/punky/images/logo.png" />

**Comment by seanlarkin** [comment]
Fixed!

**Comment by seanlarkin** [comment]
I can't seem to close this ticket. Could you, @Greg-Boggs ?
