### ISSUE TITLE
Rerouted paths

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#333]
In reviewing the site, I noticed that we've changed many of our routes with the redesign. I assume you've thought this through, but I would like to discuss. At the very least, we need to do some careful routing and even then risk negatively impacting our Google juice.

If we decide to change paths, than our Amazon config files need to handle the rerouting.

@MadouPDX Assigning to you first to discuss.

**Comment by MadouPDX** [comment]
64% of our total traffic in 2016 is from search, but 85% of that is to blog posts. Most of the other search traffic goes straight to the home page.

Basically, our top level landing pages don't have much juice, so we should be fine with 301 redirects. I'm happy to put together that routing spreadsheet...

**Comment by levelos** [comment]
At the least, we'd need to reroute all of top level _and_ sub pages for `team`, `expertise` and `work`. Doing this type of a global pattern based rerouting is tricker with a static site as well since we don't have a true web server to manage it for us.

**Comment by levelos** [comment]
All mapped back to original routes.
