### ISSUE TITLE
Blog tagging / categories and URLs

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#334]
Team - I'd like to open a ticket to discuss how we're handling blog categories. There are a couple issues with the current approach.

* Is the intent to lost all of our historical tagging? I'm not sure that's a good idea. I'm not seeing the original tags showing on the new blog detail pages.
* In addition, the tag landing pages are very important and we cannot lose those, E.g., `http://thinkshout.com/blog/category/redhen/`. We have always sent those paths out over the years as key destinations to gather information about a particular topic. And others, like the one for Drupal Planet, are integrated with other systems. Those landing pages must also retain their RSS feeds.
* The category selection cannot use a query string. E.g., `http://localhost:4000/blog/?category=technology-and-innovation` would need to be `http://localhost:4000/blog/category/technology-and-innovation`. But that won't work as that's the historic route for the tag.

**Comment by MadouPDX** [comment]
Agreed that we don't want to eliminate historical tagging. This is mostly important for the collections, as they only traffic to those pages appears to be coming from us linking directly to them. (Tag pages accounts for (0.04% of our total traffic in 2016; 0.06% for all of 2015).

We should probably talk about bullet number 3 as a team.

**Comment by komejo** [comment]
Categories converted to topics, URL strings eliminated. The other tagging tasks are covered in separate issues, so closing this.
