### ISSUE TITLE
Convert topics to a collection

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#340]
As discussed, topics need to have their own landing pages, E.g., `blog/topic/content-strategy`. This can be achieved by making them a collection and having the layout for that collection loop through and grab every blog post with that topic.

- [x] Remove list of topics from blog posts, they should only reference the slug of the chosen topic.
- [x] Use the topics collection to create the topic selector drop down
- [x] Alter the current blog index page to filter by topic when applicable

**Comment by komejo** [comment]
Completed.
