### ISSUE TITLE
Update how tags are displayed

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#345]

**Comment by levelos** [comment]
Spacing, links, etc.

**Comment by levelos** [comment]
This is largely done, @komejo. The tags are now displayed as links and the tag landing page and RSS feeds are in place. Please give it a final review and last bit of polish. Those pages don't need to look great, just not awful.

**Comment by komejo** [comment]
Themed and ready for review. Note: you make have to run `bundle install` when you pull as we are now running jekyll 3.1.2.

**Comment by levelos** [comment]
Tag styling is broken:

![image](https://cloud.githubusercontent.com/assets/104897/13798397/321cef6c-ead3-11e5-894b-5aaa89e56a92.png)

**Comment by heypaxton** [comment]
213e9ff -- Update tag style
