### ISSUE TITLE
Not properly using the clients data file

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#350]
Client list is currently hard coded in `select-clients.html`. The finishing touches are still being put on the final list and it will be grouped by vertical.

**Comment by levelos** [comment]
@MadouPDX to finalize content with then hand to @komejo

**Comment by rosalynhart** [comment]
https://docs.google.com/a/thinkshout.com/spreadsheets/d/1-aqdHWspKr6v8m-I2t5J20wlMOP7h_tzERkgV2X69Rg/edit?usp=sharing

**Comment by rosalynhart** [comment]
Current categories are:
Crisis Response
Cultural
Education
Environment
Health
Philanthropy
Social Justice & Human Rights
Tech
Wild/Animal Welfare

Recommendations:
Animal Welfare
Cultural
Education
Environment
Health and Athletics
Human Services (would include Crisis Response and the food banks)
Philanthropy
Social Justice and Human Rights
Technology

**Comment by rosalynhart** [comment]
@MadouPDX Please review my category recommendations - thanks!

**Comment by rosalynhart** [comment]
Recommended categories above have been approved by @MadouPDX.
