### ISSUE TITLE
[1 hr] Truncated width of paragraph text

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#358]
In cases with an image, are we intentionally truncating paragraph text? E.g., see below:

![image](https://cloud.githubusercontent.com/assets/104897/13711476/a18094a2-e773-11e5-8587-70c283e411b4.png)

As opposed to:

![image](https://cloud.githubusercontent.com/assets/104897/13711486/b2a248d4-e773-11e5-8aeb-f1a15441389d.png)

**Comment by levelos** [comment]
@jessicatate, for you to weight in on.

**Comment by jessicatate** [comment]
Great question! The purpose of truncating the paragraph is to insure the length of one line doesn't exceed a certain amount of characters for readability. Ideally, the maximum character count we should have on one line is 66-72. Another example of this is seen here http://thinkshout.github.io/thinkshout/work/ on intro of the page.

With all of this said, I might have a solution for this section to avoid the awkward space. We could do something like seen here: http://thinkshout.github.io/thinkshout/careers/

**Comment by rosalynhart** [comment]
@levelos Assigning back to you for a decision on this.

**Comment by levelos** [comment]
@jessicatate Do you mean the centering? I do like that, but definitely not a launch priority. Moving to post-launch.

**Comment by rosalynhart** [comment]
@levelos - planning on working on this during sprint with the approach recommended above, which you said you liked. Let us know if we should make a shift at all.

**Comment by jessicatate** [comment]
@levelos I was actually referencing the section that has the 3/4 body copy and the call to action button to the right.

**Comment by levelos** [comment]
@jessicatate Yeah, I like that. I think the careers landing page is one of nicest layouts.
