### ISSUE TITLE
Change call to action block in blog posts from Salesforce training

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#362]
NTC for now - Brett will provide text

**Comment by komejo** [comment]
This needs to have a global default and an optional per-post override.

**Comment by rosalynhart** [comment]
@skgutowski - @MadouPDX has asked that you draft this.
This is a block that will appear on all blog posts by default and can be over-ridden on individual posts if needed. Example appears here:
http://thinkshout.github.io/thinkshout/blog/2016/01/drupal-global-events-portland

Can you draft this by noon on Tuesday?

For launch, we want it to talk about NTC instead of Salesforce.
There should be:
Header
Short sentence
Call to action with link
Image

@komejo set this up so let him know if you have any q's.
@komejo will implement once text is written.

**Comment by rosalynhart** [comment]
Content here: https://docs.google.com/a/thinkshout.com/document/d/1-MbFtDeU2u6bKseAC2TYo3EwoUeTXQuIit3Vmyk5hCA/edit?usp=sharing.

Please review and approve, @MadouPDX

**Comment by MadouPDX** [comment]
Updated and approved.

**Comment by rosalynhart** [comment]
There is also an issue with the padding on the gray box in this block - should be the size of the photo
