### ISSUE TITLE
Reviews/edits of SPLC case study

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#365]
- [x] @tauno to add a few sentences about the infrastructure

- [x] @skgutowski and to review/edit for clarity

- [x] @natanialeclerc to review/edit for clarity

- [x] Final review by @levelos 

Text here: https://docs.google.com/a/thinkshout.com/document/d/1H0pHJ9qzojpO5FA9mBeqe7qGxjWiHw3fPNF0WXB_zBY/edit?usp=sharing

**Comment by rosalynhart** [comment]
Assigning to @natanialeclerc for first round review. @tauno can add his infrastructure sentence once he has a break from FH today.

**Comment by natanialeclerc** [comment]
suggestions added to the doc - feel free to accept/reject as needed!

**Comment by rosalynhart** [comment]
Assigning to @tauno for adding a couple sentences about infrastructure. Tauno, let me know if I can be of any assistance there.

**Comment by tauno** [comment]
Added some text. Please review and make suggestions. I added a possible graphic of the hatemap traffic spike if that adds anything.

**Comment by skgutowski** [comment]
My edits are in Passing to Lev for review, and to accept/reject suggestions.

**Comment by levelos** [comment]
Team, my edits are in. I made some suggested changes and have a couple of questions in there as comments. @rosalynhart, who owns the final edits and adding to the site?

**Comment by rosalynhart** [comment]
Assigning back to @MadouPDX for final content edits, then will assign out for content placement.

**Comment by MadouPDX** [comment]
There's one more question for @tauno, but approved other than that.

**Comment by rosalynhart** [comment]
Moving this over to @komejo to plug in the content. Joe, @jessicatate will be preparing new case study images.

**Comment by komejo** [comment]
Added text and updated url, over to Jessica for image placement.
