### ISSUE TITLE
Update content on Open Source Contributions page

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#368]
@levelos will be updating content directly on the site rather than in the Google doc.

**Comment by levelos** [comment]
I update the intro text throughout the site and refactored our approach to rendering the open source page. There's now a data file containing our list of contributions which we can maintain over time.

Post-launch, I want to revisit the message and goals of this page. Perhaps including the usage stats and sorting by those as opposed to alphanumerically.
