### ISSUE TITLE
Fix link issues

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#370]
- [x] External links throughout site should open on a new tab

- [x] External links should not have http://thinkshout.github.io/thinkshout appended to the beginning

**Comment by AmyVS** [comment]
- [x] b-corp
 - [x] footer
 - [x] about

- [x] Social media
 - [x] Facebook
 - [x] Twitter

- [ ] blogs

- [ ] case studies

**Comment by AmyVS** [comment]
Kickin' this one over to @komejo to take care of external blog links.

**Comment by komejo** [comment]
Checking blog-post and case-study pages for external sites w. jQuery.

**Comment by rosalynhart** [comment]
Is this one done @komejo? Sounds like it but not sure.
