### ISSUE TITLE
[3-4 hrs] Fix cropping of team member images on mobile

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#371]
Team member images on landscape for mobile devices - focus area can be inappropriate
- solution (same as old site): crop images to square when on mobile.

**Comment by rosalynhart** [comment]
1 hour for code
2 hours for creating and uploading square images
OR
Could do a fixed height but would need to determine appropriate fixed height for each device.

**Comment by heypaxton** [comment]
Tip: Set fixed width height of image wrapper and set overflow hidden to wrapper. Image width should be 100% inside wrapper for image.

**Comment by jessicatate** [comment]
This is resolved.
