### ISSUE TITLE
Mobile - issues with lines in newsletter block

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#375]
- [x] Newsletter block, email address border-bottom line has curves (it’s cause the form styles change. Check the /contact/ page to see an example of rounded input boxes on mobile)

- [x] This issue was noted in Firefox but is likely related to the above: border-bottom line on email address off by 1 pixel

**Comment by heypaxton** [comment]
0ef7e95 Put border on newsletter on form element and use @placeholder function

This also fixes the automatic border radius on iOS.
