### ISSUE TITLE
Remove what we do lorem ipsum

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#378]
![image](https://cloud.githubusercontent.com/assets/104897/13714196/ffc5f738-e781-11e5-9be6-1ca0bc67bb77.png)

**Comment by rosalynhart** [comment]
@levelos - @MadouPDX said you could write this and Natania can proofread/polish.

**Comment by levelos** [comment]
I believe the current text under "who we are" actually belongs under "what we do". Then, of course, we'd need text for "who we are".

**Comment by rosalynhart** [comment]
Thanks @levelos. What's currently on the site matches the content doc, but you're right that it doesn't really make sense. @MadouPDX will write a sentence for Who We Are. I'll open a new ticket for that.
