### ISSUE TITLE
Show other (or related) case studies at the bottom of a case study

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#379]
@MadouPDX, I worry that when browsing a case study, one gets lost with no where to go. Thoughts listing the other case studies at the bottom?

**Comment by MadouPDX** [comment]
I think that we should do this, but it feels a little time intensive, and may require some design. It would be fantastic to show a related case study.

**Comment by levelos** [comment]
@jessicatate and @MadouPDX, up to you if this looks alright or any quick suggestions. Happy to leave it out if it detracts.
