### ISSUE TITLE
Update case study images

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#381]
- [x] SPLC site redesign
Hatemap, plus cross-device screenshots
- [x] Ocean Outcomes
http://thinkshout.github.io/thinkshout/work/ocean-outcomes/
- [x] Colorado Trust
http://thinkshout.github.io/thinkshout/work/colorado-trust/
- [x] SPLC Selma microsite
http://thinkshout.github.io/thinkshout/work/splc-selma/

**Comment by skgutowski** [comment]
There's an issue with how SPLC scales in the browser, so I'm omitting the tablet and ios screenshots for now.

**Comment by rosalynhart** [comment]
All saved here https://drive.google.com/open?id=0B0UYz2Y10gXseTQxWDJZZHJseEk and the SPLC issue mentioned above is resolved. Over to @jessicatate for templating.
