### ISSUE TITLE
[1 hr] On 3/28: Change call to action block in blog posts to DrupalCon

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#388]

**Comment by rosalynhart** [comment]
On 3/28, need to change to DrupalCon

**Comment by heypaxton** [comment]
This can be changed in `_data/blog-cta.yml`. However we need to add functionality to override on a per post basis.

**Comment by rosalynhart** [comment]
Will create a separate issue for the per-post override.

**Comment by heypaxton** [comment]
related to #431

**Comment by rosalynhart** [comment]
@skgutowski - Do you want to tackle this? It's changing content and an image in the .yml file. @heypaxton can train you. If you don't have capacity, we can do this during Thursday's sprint.

**Comment by skgutowski** [comment]
Use this:

"Meet the ThinkShout team at DrupalCon New Orleans"

"Have a question about what's in store for our [Drupal contributions](https://thinkshout.com/expertise/open-source/)? Want to learn a little more about working at ThinkShout? Stop by booth 216 - we'd love to chat! And be sure to check out our business showcase session"

Photo attached. 
![neworleans2016_0](https://cloud.githubusercontent.com/assets/6342634/14189512/8cdf4956-f742-11e5-909e-828c209769ad.jpg)

**Comment by rosalynhart** [comment]
Should link to: https://events.drupal.org/neworleans2016

**Comment by AmyVS** [comment]
New blog-cta info updated. I needed to adjust the photo with some gray padding on the top and bottom so the image looked centered for most devices, otherwise the image appears top and right aligned. Vertically centering the blog-cta image might require more time, but probably worth the investment.
