### ISSUE TITLE
Landing page intro text styling is inconsistent

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#395]
Our work:
![image](https://cloud.githubusercontent.com/assets/104897/13790062/d9df1994-eaa3-11e5-94dc-133eb03476e6.png)

vs all other:
![image](https://cloud.githubusercontent.com/assets/104897/13790067/e41ebee6-eaa3-11e5-8835-2c3a2c2b50c3.png)

It should all be the same. I'm in favor of the former, bolder style.

**Comment by AmyVS** [comment]
I did a quick look-over - it appears to be an outlier page. Nice catch!
