### ISSUE TITLE
Changes to upcoming events on Contact page

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#399]
- [x] @MadouPDX to provide updated copy about these events

@heypaxton to make other changes:
- [x] Second event should be DrupalCon

- [x] Links should open in new window

**Comment by MadouPDX** [comment]
NTC

With over 100 educational sessions, an exhibit hall highlighting the latest nonprofit products and services, and networking events each day, the NTC is an event you shouldn't miss. We’ll be presenting on user experience on 3rd party systems [http://www.nten.org/session/if-i-only-had-a-framework-crafting-user-experiences-across-3rd-party-systems/] and digital storytelling [http://www.nten.org/session/show-dont-tell-online-storytelling-through-digital-media/] this year. Want to chat with us in person about the work we do? Stop by booth 715! [http://www.nten.org/ntc/at-the-ntc/exhibit-hall/]

DrupalCon New Orleans

Join us in the Big Easy for North America's premier Drupal event. New Orleans in the spring time is a city like no other, and we'll be sending our team there to present, learn, and network.

[We'll add to the NO description once we know what sessions have been selected and who's going, but this will do for now.]
