### ISSUE TITLE
Left justified container alignment - home page featured blog post

### ISSUE THREAD

**Issue by AmyVS** [thinkshout/thinkshout#401]
Seems like it's more of an issue with larger screens - probably a post-launch issue: 

![blog-container](https://cloud.githubusercontent.com/assets/6893715/13795994/723fb3a2-eac1-11e5-9275-da05bdc90bd7.png)

**Comment by rosalynhart** [comment]
Per discussion with @heypaxton - this fix may not be possible due to how the containers are structured.

**Comment by komejo** [comment]
Fixed in ts-redesign-dev, ready for review.

**Comment by komejo** [comment]
This went live a while ago, closing.
