### ISSUE TITLE
Read more/read less on team member blog posts is flipped

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#402]

**Comment by AmyVS** [comment]
@heypaxton - looks like the nth-child and `display: none` functionality on the team member detail page blog box isn't currently working. I tried adding `!important` and was able to display the three most current blog posts, but was unable to do the same for the JS portion of the changes in css, and figured there's gotta be a better way. The "See more" and "view less" toggles are working inversely of how they are intended. Talk more tomorrow about this?

**Comment by heypaxton** [comment]
Updated reveal functionality
Use jquery `gt()` function to determine greater than three posts
