### ISSUE TITLE
Global link styles

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#407]
It appears we are missing global link styles and they are targeted at _too_ specific sections. E..g, why would inline links on a blog be different than elsewhere? See issue on contact page:

![image](https://cloud.githubusercontent.com/assets/104897/13798355/d4d29064-ead2-11e5-93f4-71077dd9a356.png)

**Comment by levelos** [comment]
Another example of where this is an issue. This is a must fix before we can launch.

![image](https://cloud.githubusercontent.com/assets/104897/13818206/395be380-eb52-11e5-9ba2-977a7dbc0c29.png)

**Comment by AmyVS** [comment]
This code simply changes all links globally to orange. Adding interactivity, such as underline, was intentionally not included globally - it would create additional bugs where we would need to strip out that functionality (elements such as pagers, underlines on carets, etc...).
