### ISSUE TITLE
[2-3 hrs] [META] Reconsider use of single-use layouts and the need for a basic page

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#409]
Right now, we have `_layouts/privacy.html` and then `privacy.md` and if we're editing the privacy content, we have to go to two places.

Ideally, the layouts needs to be structured to allow us to create a page on the site using a basic or default template and without the need to create additional site elements such as layouts.

The structure of the templates also prohibits the use of Markdown for content for the main body of something like the privacy and thank you pages.

Obviously post-launch, I'm just capturing. It's important for long term maintainability.

**Comment by heypaxton** [comment]
- [ ] Add basic-page.html to layouts
- [ ] Make privacy and other basic pages inherit layout
