### ISSUE TITLE
iPhone 5 - 2 homepage issues

### ISSUE THREAD

**Issue by jessicatate** [thinkshout/thinkshout#413]
Add white overlay (or opacity on background) to home page hero
![img_0486](https://cloud.githubusercontent.com/assets/4450483/13819705/ac0e7460-eb57-11e5-81cb-524da97ab3ac.PNG)

Form is misaligned 
![img_0487](https://cloud.githubusercontent.com/assets/4450483/13819706/ac14407a-eb57-11e5-906d-e71fec2dcd9b.PNG)

**Comment by AmyVS** [comment]
Both issues are fixed. The fix for the second one: 8af1354c2
