### ISSUE TITLE
[1-2 hrs] Samsung Tablet - /blog

### ISSUE THREAD

**Issue by jessicatate** [thinkshout/thinkshout#418]
On /blog unable to select filter options via tap

Missing functionality

**Comment by jessicatate** [comment]
Actually, on page reload this fixed itself. I do notice sometimes the styling of the form comes in after a few seconds. Not an issue at the moment

**Comment by jessicatate** [comment]
Actually this is still an issue, but not always an issue. Also we have "Select an option" displayed after the user selects a topic. I'm confused. See me.

**Comment by heypaxton** [comment]
I was able to replicate this. I'll install browsersync to troubleshoot this issue.
