### ISSUE TITLE
Default hero image on featured blog posts

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#420]
The default hero image (of the legos) should NOT appear on individual blog posts - as it does on http://thinkshout.github.io/thinkshout/blog/2016/02/porting-thinkshout-to-drupal-8, but SHOULD appear on all topic landing pages, as it does not on http://thinkshout.github.io/thinkshout/blog/topic/strategy/

**Comment by rosalynhart** [comment]
In addition - the hero image on Drupal Global Events post should not be the Selma image. http://thinkshout.github.io/thinkshout/blog/2016/01/drupal-global-events-portland

**Comment by komejo** [comment]
Fixed.
