### ISSUE TITLE
Contextual hero images for all featured blog posts

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#421]

**Comment by rosalynhart** [comment]
Someone - likely the authors of each featured blog post - will need to determine an image to use as their hero image.

**Comment by rosalynhart** [comment]
@jessicatate can provide guidelines for content authors on image size and dimensions.

**Comment by jessicatate** [comment]
Originally, I believe we planned to only feature one "Featured Blog Post" site-wide. I didn't account for each category to have its own featured blog post. This is especially true when you consider the current situation with Strategy & Design (https://thinkshout.com/blog/topic/strategy/). In this case, our "featured" post is also the most recent blog post which I expect to happen often. Additionally, the topic filter is listed below the hero so I believe it's a little unexpected that the hero element will change. What are your thoughts @levelos?
