### ISSUE TITLE
/team - grid issues at certain sizes

### ISSUE THREAD

**Issue by jessicatate** [thinkshout/thinkshout#423]
Looks like Tauno & Stephanie are all alone. :(

desktop
<img width="1064" alt="screen shot 2016-03-16 at 10 21 11 am" src="https://cloud.githubusercontent.com/assets/4450483/13821903/d7875324-eb60-11e5-8a8c-b339a392afda.png">

tablet
<img width="873" alt="screen shot 2016-03-16 at 10 21 52 am" src="https://cloud.githubusercontent.com/assets/4450483/13821920/eee841ea-eb60-11e5-8fe6-8ec4ec165e64.png">

large desktop
<img width="1437" alt="screen shot 2016-03-16 at 10 22 16 am" src="https://cloud.githubusercontent.com/assets/4450483/13821940/ffc84000-eb60-11e5-827d-24b54be392cb.png">

**Comment by rosalynhart** [comment]
Maybe related to https://github.com/thinkshout/thinkshout/issues/414
