### ISSUE TITLE
[4-5 hrs] IE 9 Issues

### ISSUE THREAD

**Issue by jessicatate** [thinkshout/thinkshout#424]
A couple issues for IE9...

Section doubled
<img width="1421" alt="screen shot 2016-03-16 at 12 00 44 pm" src="https://cloud.githubusercontent.com/assets/4450483/13825434/cc781aa4-eb6f-11e5-8b9d-b123c155600d.png">

Missing input form helper text
<img width="866" alt="screen shot 2016-03-16 at 12 01 20 pm" src="https://cloud.githubusercontent.com/assets/4450483/13825448/e1bdc26a-eb6f-11e5-919c-f55b55c3f043.png">

<img width="693" alt="screen shot 2016-03-16 at 12 03 49 pm" src="https://cloud.githubusercontent.com/assets/4450483/13825462/ea490fac-eb6f-11e5-918d-e7bf6d946dab.png">

No gradients 
<img width="1406" alt="screen shot 2016-03-16 at 12 03 27 pm" src="https://cloud.githubusercontent.com/assets/4450483/13825489/032715d2-eb70-11e5-88ef-7434f0e6c234.png">

**Comment by rosalynhart** [comment]
Priority TBD once we work through other items

**Comment by MadouPDX** [comment]
We've had just 26 visits from IE 9 so far in 2016. Not a launch priority.

**Comment by rosalynhart** [comment]
Make an IE stylesheet
Gradients not a priority - may be difficult to make them exact

**Comment by komejo** [comment]
Fixed the placeholders, gradients. Couldn't replicate the doubling issue.

**Comment by komejo** [comment]
Fixed.
