### ISSUE TITLE
Fix spacing on home page featured case studies

### ISSUE THREAD

**Issue by rosalynhart** [thinkshout/thinkshout#435]
Spacing can be tight around case studies blurbs on certain sizes, either on the right side or bottom of the text.

**Comment by heypaxton** [comment]
<img width="436" alt="screen shot 2016-03-28 at 3 24 17 pm" src="https://cloud.githubusercontent.com/assets/543800/14092093/456e3ce4-f4f9-11e5-94ad-5097100c5107.png">
<img width="385" alt="screen shot 2016-03-28 at 3 24 49 pm" src="https://cloud.githubusercontent.com/assets/543800/14092094/457b5a1e-f4f9-11e5-89eb-384077f7b4dc.png">

Some of the spacing is a little close to the edge.
