### ISSUE TITLE
Featured Blog Post header on homepage doesn't change.

### ISSUE THREAD

**Issue by skgutowski** [thinkshout/thinkshout#444]
This might not be a bug, but I switched out the featured blog on the homepage and added a new featured header image. While the new header shows up on the blog page, and the blog itself, it does not appear on the homepage - the homepage still shows the lego image.

**Comment by komejo** [comment]
Good catch, this is fixed and on stage for review: http://stage.thinkshout.com/

**Comment by levelos** [comment]
We should be sure this is fixed as part of this batch of work.

**Comment by komejo** [comment]
Confirmed working and live, closing.
