### ISSUE TITLE
Missing images and wonky formatting on older blog post

### ISSUE THREAD

**Issue by nrackleff** [thinkshout/thinkshout#449]
I’m looking at an older blog post on ThinkShout.com. https://thinkshout.com/blog/2012/06/sean/redhen-crm-part-2/ The images are missing and some of the headings are pulled way over to the left edge of the browser. The images are pointing to a dropbox folder.

**Comment by komejo** [comment]
Was able to fix the h4 tags, but the images are lost. Have edited the post to remove the broken images and added a note directing users to a more recent update.

**Comment by nrackleff** [comment]
@komejo Still looks wonky to me. Is it just not pushed live yet?

**Comment by komejo** [comment]
@nrackleff Correct, will go live the next time @skgutowski does a prod push. Review here: http://stage.thinkshout.com/blog/2012/06/sean/redhen-crm-part-2/

**Comment by nrackleff** [comment]
Looks great. :-)
