### ISSUE TITLE
Do not use a default header image for blog posts

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#480]
Blog posts should either provide their own hero/header images, or have none. In other words, every blog post should _not_ have the lego figurine header image.

Related, @skgutowski and I chatted and we agree that as an editorial rule, every featured blog post will have a unique header image.

/cc @MadouPDX

**Comment by komejo** [comment]
There is currently no default header image for blog posts. Header image (and alt text) are set by the following in the frontmatter:  
`header-image:  
header-image-alt:`

As long as every featured / homepage post has a unique header image, no changes to code are required.
