### ISSUE TITLE
Background images poorly cropped on wider resolutions

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#481]
In particular with case studies, and especially bad on the home page.

E.g., 
![image](https://cloud.githubusercontent.com/assets/104897/16858349/1c3f22de-49db-11e6-9ac0-e5b98ff0d4a6.png)

/cc @MadouPDX @skgutowski

**Comment by jessicatate** [comment]
Update styling for Our Work page to match the new homepage

**Comment by AmyVS** [comment]
Closing, since this ticket is no longer applicable. Please refer to #527
