### ISSUE TITLE
Home page spacing

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#483]
@MadouPDX and I agree that we need some space on the home page between the page header and case studies. Especially true on wider resolutions.

Too much going on.

![image](https://cloud.githubusercontent.com/assets/104897/16858473/e64a998c-49db-11e6-86e2-1994c116a3a3.png)

**Comment by jessicatate** [comment]
This is music to my ears. I've had concerns about this from the very beginning but I was out voted. There is actually a design for the space. I'll make sure it happens.

**Comment by komejo** [comment]
Fixed in master.

**Comment by levelos** [comment]
Reverted commit, needs additional work as just the spacing doesn't do it.
