### ISSUE TITLE
Title Wrap on Related Blog Tiles

### ISSUE THREAD

**Issue by AmyVS** [thinkshout/thinkshout#524]
Looks like titles can get chopped off on the related blog tiles, such as this one:
![related_blog](https://cloud.githubusercontent.com/assets/6893715/20506214/4b432cd2-b007-11e6-91a8-2b7b451460f0.png)

I propose wrapping titles so they fit within the tile element.

**Comment by jessicatate** [comment]
@AmyVS Can you check to see if this is still an issue?

**Comment by AmyVS** [comment]
@jessicatate - yep, still an issue.

**Comment by heypaxton** [comment]
@traceywhitney @jessicatate This change can be reviewed here:
http://stage.thinkshout.com/blog/2016/12/is-november-2016-and-outlier-or-the-new-normal/

**Comment by traceywhitney** [comment]
Hey @heypaxton! Took a look and for me it's still cutting the title off as I shrink the screen, up until the break point and then it looks great again. See the progression below:

<img width="1437" alt="screen shot 2016-12-15 at 12 12 55 pm" src="https://cloud.githubusercontent.com/assets/23063776/21240434/26e1604a-c2c0-11e6-885d-77dc53cd1234.png">

<img width="1434" alt="screen shot 2016-12-15 at 12 13 18 pm" src="https://cloud.githubusercontent.com/assets/23063776/21240442/3255d0f0-c2c0-11e6-9faf-1f3d6b5eeefc.png">

<img width="1418" alt="screen shot 2016-12-15 at 12 13 30 pm" src="https://cloud.githubusercontent.com/assets/23063776/21240449/37afb96c-c2c0-11e6-89b2-cde33870cb96.png">

**Comment by heypaxton** [comment]
@traceywhitney That looks like browser caching. Here is the new one where the title wraps instead of staying on one line.
<img width="1472" alt="screen shot 2016-12-15 at 12 48 50 pm" src="https://cloud.githubusercontent.com/assets/543800/21241520/dd952c6e-c2c4-11e6-9099-d4cdb30bae04.png">

**Comment by traceywhitney** [comment]
Righto, sorry about that, lesson learned ;)

Looks good!
