### ISSUE TITLE
Our Work Updates

### ISSUE THREAD

**Issue by AmyVS** [thinkshout/thinkshout#527]
Following the styling on the homepage, please update the Our Work images.

- [x] Remove full-width images and fill to container

- [ ] Add option for one-column and two-column (this will likely be a challenge with a static site)

**Comment by traceywhitney** [comment]
@AmyVS, Jessica has updated the designs for the Our Work page here: https://projects.invisionapp.com/d/main#/console/4740800/211660867/preview. Just awaiting Lev's approval and then we can continue the updates. The goal is to have the updates on this page completed by the end of the year, as billable work allows of course.

**Comment by traceywhitney** [comment]
We can move forward with updates to the portfolio images _above_ the orange section. Note Jessica's comments #1-4 in Invision.

**Comment by traceywhitney** [comment]
Thanks for taking over this ticket @komejo! We have a series of updates that we're in the process of making to the Our Work page on ts.com, and this ticket refers specifically to the case study images on the page. We are changing them from being full width to filling to a container. Jessica has put the updated designs on invision: https://projects.invisionapp.com/d/main#/console/4740800/211660867/preview. Note that there are additional changes to the page beyond just the images (i.e. the CTA block), but those are still under discussion and Jessica will be working on another round of designs related to those changes later this week. So for now, please just focus on her comments #1-#4, in regards to the case study images. Thank you!

**Comment by komejo** [comment]
Done and on develop.

**Comment by traceywhitney** [comment]
Thanks Joe! Did you make these changes in a separate channel? If so, (not that I completely understand yet but I'll take a shot at it) Lev was explaining to me that as long as the changes are made in a separate channel they can be merged into the master/staging environment without overwriting Stephanie's content updates. Is that not the case here?

**Comment by jessicatate** [comment]
@komejo We need to add a link to see all case studies.
Can we implement this tiny change? 

![screen shot 2017-01-18 at 12 09 26 pm](https://cloud.githubusercontent.com/assets/4450483/22081083/07e1a3cc-dd77-11e6-89ac-9bbb24826c03.png)

**Comment by jessicatate** [comment]
@komejo Two more updates. 

1. On Mobile, can we hide the teaser description or reduce type size significantly?
2. Can we reduce the space between case studies? 

![screen shot 2017-01-18 at 12 14 59 pm](https://cloud.githubusercontent.com/assets/4450483/22081383/3fb82db0-dd78-11e6-87fc-e9e6874035f1.png)

**Comment by komejo** [comment]
Mobile styling updating - on develop.

**Comment by traceywhitney** [comment]
Just tried out my local and it worked great! Thanks again for helping me set that up yesterday @komejo! Mobile styling looks good to me, but let me know once the "See all case studies" link is also finished and then I'll assign this ticket back to Jessica to finish up the QA.

**Comment by komejo** [comment]
Archive page merged in and Archive link added. In develop branch for review.

**Comment by traceywhitney** [comment]
Looks great to me @komejo good job - assigning to @jessicatate for final QA/approval.

**Comment by traceywhitney** [comment]
Link to original archive ticket: https://github.com/thinkshout/thinkshout/issues/528. Closed after merge.

**Comment by jessicatate** [comment]
Hey @komejo. Sending over a few more minor changes. The page just seemed a little off to me. Your work is great as always.

1. Update the Client name to font-size: 1.2rem (1.png)
2. Update the description to  font-size: .85rem (1.png)
3. Reduce the margin between case studies to margin: 0 0 3rem (2.png). Quite note: When I reduced the margin it looks like the line for the "see all case studies" link is a little close now. Maybe some padding on that could be nice?

**Comment by traceywhitney** [comment]
@komejo - not sure if you saw this in the Slack channel already but when you incorporate this last bit of feedback from Jessica please also "hide" the See All Case Studies link until we can decide how to approach the older case studies. Sorry to have you add it and then take it away again, but hopefully the work can be saved and then just copied back in again when we're ready for it.

**Comment by komejo** [comment]
Done and on `develop` branch for review. Link commented out and additional temp padding added.

**Comment by traceywhitney** [comment]
Thanks @komejo! @jessicatate please take a look when you get a chance!

**Comment by jessicatate** [comment]
@komejo Would you mind taking a look at this screenshot one more time? https://cloud.githubusercontent.com/assets/4450483/22158281/6adacce0-def0-11e6-8b3b-dbe40f2a384a.png I'm not seeing it on develop. Thanks!

**Comment by jessicatate** [comment]
@komejo I'm also not seeing the "see all case studies" hidden on develop.

**Comment by traceywhitney** [comment]
@komejo our work archive page should still be live even though we're hiding the link. https://thinkshout.com/work/archive

**Comment by komejo** [comment]
Wha-la! https://thinkshout.com/work/archive/

Interesting note - on a local machine, a permalink of work/archive works - because it creates a page called archive.html in the /work/ directory. On the server though, it does not have the setting that allows pages without file extensions to be seen. (it was live at /work/archive.html)

I fixed it  by changing the permalink from `work/archive` to `work/archive/`.

**Comment by traceywhitney** [comment]
Thanks Joe! Looks good!
