### ISSUE TITLE
Our Work Archive

### ISSUE THREAD

**Issue by AmyVS** [thinkshout/thinkshout#528]
Use two-column design of projects on homepage to create the archive page.

**Comment by traceywhitney** [comment]
@jessicatate can you remind me what the status of this ticket was when we last discussed it?

**Comment by jessicatate** [comment]
There are two things that surround this ticket:

1. We need to check on the development of the /archive page. I believe @AmyVS completed a lot of this work. 
2. We need to add a "see more" link below the featured case studies. 

The #2 duplicates an open issue noted here. https://github.com/thinkshout/thinkshout/issues/539. We can probably close the ticket I linked in lieu of keeping this open.

**Comment by jessicatate** [comment]
I can not find a /work/archive page on develop. @komejo or @AmyVS- We need a way access this page before I can QA. 

@traceywhitney Can you assign to a developer?

**Comment by traceywhitney** [comment]
Assigned. @komejo please advise.

**Comment by komejo** [comment]
Switch to branch: `git checkout issue-527` and it is at http://localhost:3000/work/archive/

**Comment by jessicatate** [comment]
@komejo Do you recommend merging this work into develop since we will be releasing it together as 1.2?
