### ISSUE TITLE
Facing History card on home page has underline on mobile response

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#532]
![image](https://cloud.githubusercontent.com/assets/104897/20680820/8732aa08-b555-11e6-90b3-0bbec5227c38.png)

**Comment by AmyVS** [comment]
@levelos - which device, browser and browser version is this happening on?

**Comment by AmyVS** [comment]
@jessicatate and I were unable to reproduce this issue on our iPhones, in Chrome tools, and other browsers. Please reopen this ticket on the off-chance this issue pops up again.
