### ISSUE TITLE
Blog Landing: Update Hero Image and Text

### ISSUE THREAD

**Issue by jessicatate** [thinkshout/thinkshout#534]
Let's changed the featured blog post hero to match the featured display on the homepage. 
Yellow title + white detail text please.

Here is a reference:
![reference](https://cloud.githubusercontent.com/assets/4450483/20682413/d085ad70-b55c-11e6-8c49-33ca026c655a.png)

Please use CSS to darken the image. We want the ability to upload a full-color image.

Thanks,

**Comment by heypaxton** [comment]
@jessicatate ready for QA. You can QA on your local.

**Comment by traceywhitney** [comment]
@jessicatate please review and approve when you get a chance!

**Comment by jessicatate** [comment]
QA confirmed. Ready to push live.
