### ISSUE TITLE
Add Link to Career Block on About Page

### ISSUE THREAD

**Issue by traceywhitney** [thinkshout/thinkshout#544]
Please add a link to the Career Page on the Career Block on the About Page https://thinkshout.com/about/. This link must have disappeared when we added workable. 

![screen shot 2016-12-12 at 5 12 26 pm](https://cloud.githubusercontent.com/assets/23063776/21123570/538c22e4-c08e-11e6-991e-611f1ed0ae92.png)

**Comment by heypaxton** [comment]
@traceywhitney this is ready for review at http://stage.thinkshout.com/about/

**Comment by traceywhitney** [comment]
Looks good, thank you!
