### ISSUE TITLE
Diversity Pledge Updates

### ISSUE THREAD

**Issue by traceywhitney** [thinkshout/thinkshout#550]
Updates to the design, IA, and CTAs based on recommendations from the Diversity Pledge.

**Comment by jessicatate** [comment]
It seems we will want to push this ticket into 1.3. I imagine this work will take a while with a couple rounds of wireframes & design.

**Comment by traceywhitney** [comment]
@nrackleff I know you already have this but here is a link to the designs in InVision! https://invis.io/9B4HHT8HA

**Comment by traceywhitney** [comment]
- [ ] tes test
