### ISSUE TITLE
[4hr] Footer changes

### ISSUE THREAD

**Issue by nrackleff** [thinkshout/thinkshout#568]
- [x] Email newsletter signup: shrink to just a bar with slight drop shadow. New height: 82px.
- [x] Default the submit to white and underline on hover.
- [x] Leave placeholder faded, but make value entered white.
- [x] Make sure footer nav reflects changes to top nav. 
- [x] Include subpages in nav. including expertise and agency sub pages.
- [x] Height of footer hero is reduced a bit. Was 544 now 390px - Jessica will provide new image. 
- [x] Smaller Bcorp logo.
- [x] Nav color should start out light orange and underline on hover. No dark orange.
- [x] Update the copyright to 2017.

https://projects.invisionapp.com/share/9B4HHT8HA

**Comment by nrackleff** [comment]
@jessicatate Let me know when you have the new footer background image ready.

**Comment by nrackleff** [comment]
@jessicatate do you want to give me a smaller version of the B Corp logo too?

**Comment by jessicatate** [comment]
![ts_footer](https://cloud.githubusercontent.com/assets/4450483/23571598/08eced56-001f-11e7-8fab-c824aa6e7055.jpg)

**Comment by jessicatate** [comment]
Updating bcorp logo to SVG.


[bcorp.zip](https://github.com/thinkshout/thinkshout/files/818107/bcorp.zip)

**Comment by nrackleff** [comment]
@jessicatate This is ready for review in the diversity-pledge branch. So far just the visual changes. The actual URL changes for the nav are not complete yet and will be covered in #569 ticket.
