### ISSUE TITLE
[4hr] Agency page

### ISSUE THREAD

**Issue by nrackleff** [thinkshout/thinkshout#570]
The Who We Are page is changing to Agency. 

Highlights:
- [x] Change the URL from /about to /agency
- [x] Remove title and start with paragraph. If worried about “Agency” title, maybe visually hidden.
- [x] New intro paragraph style. Larger and center aligned.
- [x] Consider center align title on pages that are not changing too for consistency.
- [x] Hero height 575px on new pages. Jessica to supply new hero images. 
- [x] New block with text and three sections using brand colors. 
- [x] Cursive font - Jessica needs to update to match current site. 
- [ ] Our values block might change, so do last after Jessica.
- [x] Jessica to provide already darkened image.
- [ ] Jessica to provide Corp and Pledge links. Hover can be with underline. 
- [ ] Awards and Recognition - need content. 4 columns - Jessica will provide assets. Maybe they will link somewhere. 
- [ ] Let’s work together:
    - [x] Join -> Careers
    - [x] Meet -> Team
    - [x] Partner -> Contact
[ ] Partners & Organizations - 4 column

https://projects.invisionapp.com/share/9B4HHT8HA

**Comment by jessicatate** [comment]
These are formatted for 2-up. A center crop would be great when they are 3-up on the agency page.

![ts_join](https://cloud.githubusercontent.com/assets/4450483/23572312/10dc3ff4-0023-11e7-9cd2-6114c52836fa.jpg)
![ts_meet](https://cloud.githubusercontent.com/assets/4450483/23572313/10efbdd6-0023-11e7-9c2b-1aef54b0a7fb.jpg)
![ts_partner](https://cloud.githubusercontent.com/assets/4450483/23572314/10fbb1fe-0023-11e7-9e66-fa85ead7046e.jpg)

**Comment by jessicatate** [comment]
Prosperity and Diversity

![ts_prosperity](https://cloud.githubusercontent.com/assets/4450483/23572356/7505d27e-0023-11e7-9d96-6868a9d7e015.jpg)
![ts_diversity](https://cloud.githubusercontent.com/assets/4450483/23572357/75060fe6-0023-11e7-9061-d70616c7c7ff.jpg)

**Comment by jessicatate** [comment]
I'll regroup with the team on the awards and partners section early next week and will provide assets.

**Comment by jessicatate** [comment]
Hero

![ts_agency-hero](https://cloud.githubusercontent.com/assets/4450483/23572496/4cef2096-0024-11e7-827a-a6ec804d35d2.jpg)

**Comment by JuliaDickey** [comment]
@jessicatate

When you have a second, could you send me:
[ ]- Corp and Pledge links
[ ]- Awards and recognition content

I added links for all of the partners. Could you swing by when you're in the office and confirm they're right? 

The "Our Values" section is still on hold, but the rest of the Agency page is built.
