### ISSUE TITLE
[2hr] Team Pages

### ISSUE THREAD

**Issue by nrackleff** [thinkshout/thinkshout#572]
https://projects.invisionapp.com/d/main#/console/4740800/221288047/preview 

- [x] Meet the Team changes to Team
- [x] Change URL from /team to /agency/team
- [x] Change URL of individual team pages from /team/[person] to /agency/team/[person]
- [ ] New intro paragraph replaces title and paragraph.

**Comment by JuliaDickey** [comment]
@traceywhitney Do we have the intro paragraph copy for the team page?

**Comment by traceywhitney** [comment]
@ThomasKing and @natanialeclerc can you weigh in about copy for this section? 
<img width="1233" alt="screen shot 2017-09-27 at 9 19 07 pm" src="https://user-images.githubusercontent.com/23063776/30949138-8da06e76-a3c9-11e7-8cfc-67c3437fe026.png">

@ThomasKing can also clarify the architecture, and here are the wireframes for reference (though these are deprecated since the designs) https://invis.io/Z2DP9CRMW

**Comment by natanialeclerc** [comment]
**currently the site has this**: "We lead with technical excellence, innovation, and sustainable business practices. We love projects that lead to open source contributions that serve grassroots organizers and progressive causes. We contribute back to our community daily with updates and new tools designed to make development processes and nonprofit workflows easier."

**Proposed changes**: "We're a passionate team of individuals working to create social change and cultural awareness through innovation, strategic thinking, and open source contributions. We strive to improve engagement, site performance, and amplify the important work of the progressive causes we partner with."

@ThomasKing you are more of a wordsmith, I think you said something once about "being a social change agency"....unless that was a fever dream?

**Comment by traceywhitney** [comment]
@natanialeclerc can you circle up with Thomas and determine what copy you'd like to use for this section? @jessicatate let us know about whether Team should be in the header nav.

**Comment by natanialeclerc** [comment]
Some tweaks to the above: "We are a passionate team of individuals who partner with progressive causes to create social change. We strive to optimize constituent engagement, site performance, and amplify your message through innovation, strategic thinking, and technical excellence."

**Comment by ThomasKing** [comment]
Just put a little time on the calendar this afternoon to add thoughts. Will have them in by end of day.

**Comment by ThomasKing** [comment]
Apologies — afternoon meetings ran long and I wasn't able to get to this. Will circle back in the morning.

**Comment by traceywhitney** [comment]
No major rush @ThomasKing just trying to get these open task wrapped up.
