### ISSUE TITLE
[1-2hr] Careers Page

### ISSUE THREAD

**Issue by nrackleff** [thinkshout/thinkshout#574]
- [x] Change URL to agency/careers
- [x] Change Intro paragraph
- [x] New hero - Jessica will provide
- [x] Design includes a second intro paragraph style below the hero.
- [x] Don’t indent headlines - that is mistake in comp
- [ ] Job styling does change 
- [x] "Keep me in mind" block a little different color and different height than current.

https://projects.invisionapp.com/d/main#/console/4740800/221249872/preview

**Comment by jessicatate** [comment]
![ts_careers-hero](https://cloud.githubusercontent.com/assets/4450483/23572298/faecbd2c-0022-11e7-915a-6c2db2bd1446.jpg)

**Comment by JuliaDickey** [comment]
@jessicatate @traceywhitney 

-[ ] Is the summary text on job positions the overview text? It's much shorter than the overview text in workable. I can (1) leave it as is with the dept and location showing instead, (2) load the full length of the overview text, or (3) load a trimmed version of the overview text. Let me know how you'd like to proceed.
