### ISSUE TITLE
[2-3hr] Contact Page

### ISSUE THREAD

**Issue by nrackleff** [thinkshout/thinkshout#575]
Do this last as design is possibly changing as per comments.  

- [x] Connect With Us becomes Contact - url stays the same. 
- [x] Intro paragraph and new hero
- [x] Block overlays the hero (negative top margin)
- [ ] Events layout/position might change
- [x] New featured work block looks like two-up block from home page
- [x] Featured blocks should be manually update maybe? Check the behavior of home page to see if these are automatic or curated. 

https://projects.invisionapp.com/d/main#/console/4740800/221288042/preview

**Comment by jessicatate** [comment]
![ts_contact-hero](https://cloud.githubusercontent.com/assets/4450483/23572306/075af902-0023-11e7-8956-151f38954c0a.jpg)

**Comment by JuliaDickey** [comment]
This is built out as seen in invision. I swapped the order so the form comes first followed by the orange contact info block once they wrap on mobile and small tablets.
