### ISSUE TITLE
Old staff profiles still published

### ISSUE THREAD

**Issue by tauno** [thinkshout/thinkshout#584]
They aren't visible on the team directory, but see https://thinkshout.com/team/mikem/ and https://thinkshout.com/team/jami/

**Comment by JuliaDickey** [comment]
The .md files for former employees need to be updated to "published: false" to make them no longer appear. "current-employee: false" only keeps them from being listed on the team page.

**Comment by natanialeclerc** [comment]
@JuliaDickey need me to change that or will you update? Just checking since I got pinged about it :)
