### ISSUE TITLE
Bene landing page edits

### ISSUE THREAD

**Issue by sarahvleigh** [thinkshout/thinkshout#636]
- [x] Remove client quote block
- [x] Add caption under FRGK CTA "Photo by: Another Look"
- [x] Replace device mockup image with this updated image: https://drive.google.com/open?id=1ehQ4Yt9Y1auyKoSeLsHLRUgfX-Uoamon
- [x] Add fine print under email signup that reads: "ThinkShout will send you a monthly newsletter containing the latest in best practices as well as release announcements and software updates."

**Comment by komejo** [comment]
Done and on stage: http://stage.thinkshout.com/bene/
