### ISSUE TITLE
Edits to Our Work header

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#652]
Summary current states:
> Whether it’s a simple site or a sophisticated e-commerce solution, our work excels in terms of engagement and effectiveness.

I don't think that reflects what we're highlighting.

Thoughts on changing the heading to `Featured Projects`?

**Comment by natanialeclerc** [comment]
Let's change to "Our experience spans the social good sector -- from social justice, to universities, to animal welfare. We work to create solutions that engage and inspire your audiences in meaningful ways."

**Comment by natanialeclerc** [comment]
@levelos if you're good with that let's have @komejo update!

**Comment by levelos** [comment]
Looks good!
