### ISSUE TITLE
Bullets on services landing page

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#654]
![image](https://user-images.githubusercontent.com/104897/38331524-4debb33e-3808-11e8-97a7-07eb94765a08.png)

Are we keeping these? If so, can we align left with an indent?

**Comment by natanialeclerc** [comment]
Yeah let's keep for now, we can refine it in phase 2 but these do reflect the work we can do in a quick way. 

@komejo heads up on the left align w/indent!
