### ISSUE TITLE
Case Studies

### ISSUE THREAD

**Issue by komejo** [thinkshout/thinkshout#722]
## Overview
Update the Case Studies page/template with refreshed design for NTC 2019.

## Links
Invision: https://thinkshout.invisionapp.com/d/main#/console/16643506/345636059/preview
Site Map: https://thinkshout.invisionapp.com/d/#/console/16160970/338303639/comments

## Dev [8 hrs]
- [x]  Update site header
- [x]  Client/Challenge/solution/result block
- [x]  Grey block
- [x]  Black Block
- [x]  4-up block
- [x]  Statistical block
- [x]  Related work
- [x]  Related blogs

## Theming [11 hrs]
- [x] Ensure updated header works at all sizes
- [x] Responsive theming, all sections
- [x] Complete the [Accessibility Testing Checklist](https://github.com/thinkshout/Front-End-Style-Guide/wiki/5.-Testing-tools#accessibility-testing-checklist)

## Documentation [1 hr]
- [x] Update Wiki with case study guide.

## QA/Client Feedback (R1) [5 hrs]
**All breakpoints**
- [x] Orange title (client name) shouldn't be all caps
- [x] There should be 4 types sections with text **_(this might just need to be a content curation thing and not a development thing)_**

They are:
1. Light gray intro block
2. Dark Gray quote block
3. Dark Gray summary block
4. Project overview block on white (always the first section beneath hero)

Intro sections should always be the light gray version like this one.
![screen shot 2019-02-22 at 3 24 11 pm](https://user-images.githubusercontent.com/21184833/53276882-f641d200-36b5-11e9-9205-a434f20caa29.png)

Dark gray sections should be reserved for quotes and the summary

**Desktop**
- [x] Check to make sure said title is 24 pixels
- [x] Lets make the heading (large gray title) smaller and consistent with the other new page titles we just handed over. 56 pixesl, 73 pixel line height.
- [x] Quotes look too big. Make the white quote text 36 pixels, 55 pixel line height.

**Summary (last block)** 
- [x] Main paragraph should only be 2/3 of the grid
- [x] Main paragraph text should be Gotham Bold, 20 pixels, 35 pixel line height
- [x] Text beneath orange numbers should be gotham bold, 16 pixels, 20 pixel line height
- [ ] Text beneath image on the right should be Gotham book, 13 pixels, 23 pixel line height. Hex #D9D9D9

**Tablet and mobile**
- [x] The title scales nicely now. With the decrease in size from desktop, keep the percentage it scales down the same.
- [x] Increase padding above and below gray color blocks by 50% (light and dark)

**Comment by komejo** [comment]
To help QA (and find implementation bugs) I converted https://ntc2019--thinkshout.netlify.com/work/humane-society/ and https://ntc2019--thinkshout.netlify.com/work/columbia-riverkeeper/

**Comment by vickibrown** [comment]
@komejo Nice work! You did a great job making this look good at all breakpoints without designs. Extra bonus! @brittstetson My QA is in at the top of the ticket. If @komejo gets to this while I"m gone feel free to have Sarah or Jessica review the QA.

**Comment by vickibrown** [comment]
Also, I used this to QA as well to review a more robust summary section. https://ntc-2019.thinkshout.com/

**Comment by komejo** [comment]
Updated (and simplified!) the case study content, template, and editor wiki.
