### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by komejo** [thinkshout/thinkshout#723]
## Overview
Update the homepage with refreshed design for NTC 2019. 
 
_Note: The newsletter sign up has been added to the footer, but it's low priority. Lets only tackle that if everything else gets done first._

## Links
**Invision**
https://thinkshout.invisionapp.com/share/F3QCZY3ZBDW#/345637162_home_Desktop
**Hover state for Case Study promo**
https://thinkshout.invisionapp.com/share/F3QCZY3ZBDW#/348489701_home_Desktop_Hover
Assets in Drive: https://drive.google.com/drive/folders/1ktHt6cFpitubhfWBkBxiwKnGUePD7ut8

## Dev [1 hr]
- [x] Update/streamline homepage markup & widgets

## Theming [3 hrs]
- [x] Theme hero, sections
- [x] Complete the [Accessibility Testing Checklist](https://github.com/thinkshout/Front-End-Style-Guide/wiki/5.-Testing-tools#accessibility-testing-checklist)

## Documentation [.25 hr]
- [x] Update Wiki with homepage update instructions

## QA/Client Feedback [.75 hrs]

**Comment by vickibrown** [comment]
@komejo @brittstetson just one thing here. 
On mobile, can you put lets chat on the next line?
![screen shot 2019-02-22 at 5 44 56 pm](https://user-images.githubusercontent.com/21184833/53280097-758dd080-36cb-11e9-81d0-7ecdf797b7df.png)

**Comment by komejo** [comment]
Done! Ready for client review. https://ntc2019--thinkshout.netlify.com/

**Comment by brittstetson** [comment]
@komejo over to you to address checkboxes above. SPLC images in a separate ticket

**Comment by komejo** [comment]
Done, ready for review.

**Comment by brittstetson** [comment]
@vickibrown @ThomasKing , outside of the SPLC image (which will pull from this case study) can we call this one final/ready for Lev's final review?

**Comment by ThomasKing** [comment]
Signed off for my part.

**Comment by ThomasKing** [comment]
Vicki too, also moving to done.
