### ISSUE TITLE
Case Study Image Image Curation

### ISSUE THREAD

**Issue by vickibrown** [thinkshout/thinkshout#727]
### Overview
The case studies will require a robust set of images with the new template.  These templates are large, so final jpegs will have to be scaled and cropped according to either a large or small image space in the file.

Large images should crop to: min-width: 1216px. Height can vary, currently 752px.
Small images should crop to: 592 x 330
Full width images should crop to: 2000 x 900

### Links
The new template follows this design https://thinkshout.invisionapp.com/d/main#/console/16643506/345636059/preview
Page in production https://ntc2019--thinkshout.netlify.com/work/splc/

### Assets
An image library has been started that should work for at least the first few case studies. 
https://drive.google.com/drive/folders/1m2FSW_J35q2HspAxfRdE8Aq1ILhUGwa8?usp=drive_open

In this folder you fill find images categorized by device type that have masks in them as layers. Use these masks to make jpegs of the device shot combined with screenshots for specific case studies. 

### Organization
This is a new library that will grow as we build out more case studies. We will likely reuse these images so be sure to keep the masks in tact and just add screenshots as layers to the psd. 
As more device shots are added, add them to the corresponding folder to keep the library organized.

A lightbox has been started in Shutterstock to pull from, which is where these images came from.
https://www.shutterstock.com/collections/173285593

**Comment by vickibrown** [comment]
@brittstetson I created this ticket to give @sarahvleigh all the info to work on these case study images. I just need @komejo to fill in the image specs above so @sarahvleigh can crop the images correctly.

The library will likely need to grow, but this should be a solid start.

**Comment by brittstetson** [comment]
@komejo - we'll get Sarah working on this toward the end of the week. Could you fill out those specs in the overview by midweek?

**Comment by komejo** [comment]
Updated image specs. Note that I was just measuring what's there now, if there's a better aspect ratio that can be had from rounding up a bit, go for it.
