### ISSUE TITLE
TT Case Study

### ISSUE THREAD

**Issue by natanialeclerc** [thinkshout/thinkshout#729]
### Overview TT Case Study on new site

Large images should crop to: min-width: 1216px. Height can vary, currently 752px.
Small images should crop to: 592 x 330
Full width images should crop to: 2000 x 900

### Links
Case Study: https://docs.google.com/document/d/1Ww4MWiNqP-3Dh05Sq-ZqxN2KPxOJwz6qgGGNlW34gIk/edit?usp=sharing 

### Assets
An image library has been started that should work for at least the first few case studies.
https://drive.google.com/drive/folders/1m2FSW_J35q2HspAxfRdE8Aq1ILhUGwa8?usp=drive_open

In this folder you fill find images categorized by device type that have masks in them as layers. Use these masks to make jpegs of the device shot combined with screenshots for specific case studies.

### Specific Image suggestions for this Case Study
[ ] Header image from original cast study (full width)
[ ] images at various screen sizes
[ ] Photo of illustrations used throughout the site (2 small, large)
[ ] callout of The Moment (large)

**Comment by sarahvleigh** [comment]
Images for review: https://drive.google.com/open?id=1OmMm8KCojk-g2OGYckPf9DBgdVES2Si_

**Comment by natanialeclerc** [comment]
@sarahvleigh I'm getting a 404 error?

**Comment by brittstetson** [comment]
@sarahvleigh, @natanialeclerc: Note that the content is finished, linked above. When images are ready, this can be assigned to Joe.

**Comment by vickibrown** [comment]
@brittstetson I'm going to take this one over too since I have better context for the project.

**Comment by vickibrown** [comment]
@brittstetson @natanialeclerc I updated the images in the doc and folder. If everything looks good it's good to go to Joe. 
https://docs.google.com/document/d/1Ww4MWiNqP-3Dh05Sq-ZqxN2KPxOJwz6qgGGNlW34gIk/edit?ts=5c7ef1cb

**Comment by natanialeclerc** [comment]
GREEN LIGHT! @brittstetson this is ready for @komejo ~!

**Comment by brittstetson** [comment]
@komejo first updated case study that is fully ready to build.

**Comment by komejo** [comment]
https://ntc2019--thinkshout.netlify.com/work/tolerance/

**Comment by ThomasKing** [comment]
@komejo two requests:

1. Intro paragraph is too long with two paragraphs. Let's cut the second one entirely (the content is well covered elsewhere); and
2. Let's remove the first featured image, with Dr. Seuss. The two images of the laptop are redundant.

**Comment by komejo** [comment]
Done: https://ntc2019--thinkshout.netlify.com/work/tolerance/

**Comment by brittstetson** [comment]
@ThomasKing @vickibrown any tweaks needed here?

**Comment by ThomasKing** [comment]
Signed off

**Comment by ThomasKing** [comment]
Vicki is too :) -- moving to done.

**Comment by brittstetson** [comment]
@chelseamaricle testing GitHub notifications
