### ISSUE TITLE
ABIN Case Study

### ISSUE THREAD

**Issue by natanialeclerc** [thinkshout/thinkshout#730]
### Overview
Images & content for ABIN Case Study on new site

Large images should crop to: min-width: 1216px. Height can vary, currently 752px.
Small images should crop to: 592 x 330
Full width images should crop to: 2000 x 900

### Links
Case Study: https://docs.google.com/document/d/1Ph9xXYijfV9UbHQH4phnOT7JOzEm_o_3Oc8EAfOK6k8/edit?usp=sharing

### Assets
An image library has been started that should work for at least the first few case studies.
https://drive.google.com/drive/folders/1m2FSW_J35q2HspAxfRdE8Aq1ILhUGwa8?usp=drive_open

In this folder you fill find images categorized by device type that have masks in them as layers. Use these masks to make jpegs of the device shot combined with screenshots for specific case studies.

### Specific Image suggestions for this Case Study

- [ ] Suggestions are highlighted in yellow and with a comment in the draft doc. Includes:
- [ ] Header image from original case study (full width)
- [ ] Images that reflect our deliverables: user research, persona development, landscape analysis, platform recommendations

**Comment by brittstetson** [comment]
@sarahvleigh: Note that the content is finished, linked above. When images are ready, this can be assigned to Joe.

**Comment by sarahvleigh** [comment]
To @vickibrown for review

**Comment by vickibrown** [comment]
@sarahvleigh @brittstetson images look great here. Good to pass to @komejo

**Comment by ThomasKing** [comment]
Looks good, here are a few requested content edits:

* There are five images in the first set, which creates an odd break on large screens. I suggest we remove the first image (of the woman at the white board)
* The first image in the next set (the one with three logos, including NTEN) doesn't add much. Let's use the image we're removing from the first set (woman at white board) and use it to replace this logo image.
* May we change the sequence of the image sections, bringing up the "Mentorship, Networking, Knowledge" image to the second slot, to break up the two grids?
* Lastly, we have the quotation block and summary block back-to-back, which creates a long stretch of the dark background and muddies the two sections. May we break that up with one of the image sets or consider pulling the quotation earlier into the case study sequence?

@vickibrown do you have time to vet these recommendations and send to Joe with any further detail?

**Comment by vickibrown** [comment]
@ThomasKing these all make sense to me.

**Comment by brittstetson** [comment]
@komejo see above: https://github.com/thinkshout/thinkshout/issues/730#issuecomment-470994108

**Comment by komejo** [comment]
Ready for review: https://ntc2019--thinkshout.netlify.com/work/anitab/

**Comment by sarahvleigh** [comment]
Looks great @komejo!

**Comment by ThomasKing** [comment]
Done!

**Comment by natanialeclerc** [comment]
We should add links to our blog on user research and landscape analysis here - what's the best way to note that?

**Comment by komejo** [comment]
Done: https://ntc2019--thinkshout.netlify.com/work/anitab/
