### ISSUE TITLE
CORI Case Study

### ISSUE THREAD

**Issue by natanialeclerc** [thinkshout/thinkshout#731]
### Overview
Images & content for CORI Case Study on new site

Large images should crop to: min-width: 1216px. Height can vary, currently 752px.
Small images should crop to: 592 x 330
Full width images should crop to: 2000 x 900

### Links
Case Study Draft: https://docs.google.com/document/d/1Ko4p_o0M0tFm9nwdbTJUP0EtrG5f6EKn0hvQ9Hvo4-w/edit?usp=sharing

### Assets
An image library has been started that should work for at least the first few case studies.
https://drive.google.com/drive/folders/1m2FSW_J35q2HspAxfRdE8Aq1ILhUGwa8?usp=drive_open

In this folder you fill find images categorized by device type that have masks in them as layers. Use these masks to make jpegs of the device shot combined with screenshots for specific case studies.

### Specific Image suggestions for this Case Study
- [x] Header image from original cast study (full width)
- [x] Style Tile images (large)
- [x] Site at Various screen sizes (small - large)
- [x] another site image (large)

**Comment by brittstetson** [comment]
@sarahvleigh: Note that the content is finished, linked above. When images are ready, this can be assigned to Joe.

**Comment by vickibrown** [comment]
@sarahvleigh CORI images look good.

**Comment by ThomasKing** [comment]
@vickibrown is there an image we can place between the 2nd and 3rd copy blocks? https://ntc2019--thinkshout.netlify.com/work/columbia-riverkeeper/

**Comment by vickibrown** [comment]
Pinging @sarahvleigh for this.

**Comment by sarahvleigh** [comment]
Image for @komejo to place btwn 2nd and 3rd blocks: 
https://drive.google.com/open?id=1Y4kHpMh4sRIcKEznHxklzBfqE_IX5IlL

**Comment by vickibrown** [comment]
Thanks @sarahvleigh 
@brittstetson

**Comment by brittstetson** [comment]
@komejo

**Comment by komejo** [comment]
Ready for review: http://localhost:4000/work/columbia-riverkeeper/

**Comment by komejo** [comment]
Ready for review: https://ntc2019--thinkshout.netlify.com/work/columbia-riverkeeper/

**Comment by ThomasKing** [comment]
Looks good @komejo , just an edit on the intro copy. Replace current with:

Columbia Riverkeeper’s mission is to protect and restore the water quality of the Columbia River and all life connected to it. Their previous website lacked intuitive navigation, and no longer reflected the organization’s brand. They desperately needed a site that told a compelling story, allowed visitors to easily find important information, and increase conversion for donation and newsletter subscriptions.

**Comment by vickibrown** [comment]
@komejo just one more fix. Can remove the second image and move the dark quote block to it's place. That way, the last large image will live above the two smaller images.

**Comment by komejo** [comment]
Ready for review: https://ntc2019--thinkshout.netlify.com/work/columbia-riverkeeper/

**Comment by ThomasKing** [comment]
I've never loved the title, feels a bit vague. Let's change "...engage audiences" to "...engage the community."

With that, I'm signed off.

**Comment by komejo** [comment]
Done: https://ntc2019--thinkshout.netlify.com/work/columbia-riverkeeper/
