### ISSUE TITLE
HSUS Case Study

### ISSUE THREAD

**Issue by natanialeclerc** [thinkshout/thinkshout#732]
### Overview
Images for HSUS Case Study on new site

Large images should crop to: min-width: 1216px. Height can vary, currently 752px.
Small images should crop to: 592 x 330
Full width images should crop to: 2000 x 900

### Links
Case Study Draft: https://docs.google.com/document/d/1DKQyA_e0IeHPqV93RNgC6FQMTIEwhjKhbIWoqcD5kKs/edit?usp=sharing

### Assets
An image library has been started that should work for at least the first few case studies.
https://drive.google.com/drive/folders/1m2FSW_J35q2HspAxfRdE8Aq1ILhUGwa8?usp=drive_open

In this folder you fill find images categorized by device type that have masks in them as layers. Use these masks to make jpegs of the device shot combined with screenshots for specific case studies.

### Specific Image suggestions for this Case Study
[ ] Suggestions are highlighted in yellow and with a comment in the draft doc.

**Comment by brittstetson** [comment]
@sarahvleigh note that I've put this as lowest priority given that the case study still needs to be written.

**Comment by brittstetson** [comment]
@chelseamaricle assigning you to fill out specifics as you write this case study

**Comment by chelseamaricle** [comment]
@brittstetson I actually had the image direction outline done on time. The draft was very close then, and is now done and over to Thomas for review. Can we reassign over to Sarah?

**Comment by brittstetson** [comment]
Great! Thanks @chelseamaricle.

**Comment by brittstetson** [comment]
@chelseamaricle let use these tickets to track polish as well. Can you please comment here when the draft linked above is final.

Then, when @sarahvleigh is done with images this full ticket can go to Joe for build.

**Comment by chelseamaricle** [comment]
Draft above is final @brittstetson

**Comment by sarahvleigh** [comment]
To @vickibrown for review

**Comment by komejo** [comment]
A bit confused by this - none of the Repeatable Block sections actually have text? Just bullets saying what kind of text they should have...

**Comment by chelseamaricle** [comment]
@komejo the doc in the ticket outlines the image direction for Sarah and Vicki. This doc has final copy: https://docs.google.com/document/d/1mYEMyGYn_iGLf0ArK9RQxXGpdp_fyAG7ZQ0LOAyTmms/edit

Sorry for the confusion!

**Comment by sarahvleigh** [comment]
Good to go for @komejo

**Comment by komejo** [comment]
Ready for review: https://ntc2019--thinkshout.netlify.com/work/humane-society/

**Comment by vickibrown** [comment]
@komejo let's remove the second large image in the first block. @sarahvleigh can you update the third screen in the mobile 3-up view so it starts with the images rather than "Our big fights"? 

This one: 
![Screen Shot 2019-03-08 at 12 28 52 PM](https://user-images.githubusercontent.com/21184833/54053959-c7d7f280-419d-11e9-9d4c-c0c9a8578df0.png)

**Comment by brittstetson** [comment]
@sarahvleigh assigning to you. Can you add the Dev label and assign over to @komejo when ready?

**Comment by sarahvleigh** [comment]
HSUS-Large-2.jpg is updated and ready for @komejo

**Comment by komejo** [comment]
Ready for review: https://ntc2019--thinkshout.netlify.com/work/humane-society/
