### ISSUE TITLE
FEAM Case Study

### ISSUE THREAD

**Issue by natanialeclerc** [thinkshout/thinkshout#733]
### Overview
Images & copy for FEAM Case Study on new site

Large images should crop to: min-width: 1216px. Height can vary, currently 752px.
Small images should crop to: 592 x 330
Full width images should crop to: 2000 x 900

### Links
Case Study Draft: https://docs.google.com/document/d/1umBc4NX5SDT2ylAEDKWmp7wQHgVecP_lTDhUZwPibvY/edit?usp=sharing

### Assets
An image library has been started that should work for at least the first few case studies.
https://drive.google.com/drive/folders/1m2FSW_J35q2HspAxfRdE8Aq1ILhUGwa8?usp=drive_open

In this folder you fill find images categorized by device type that have masks in them as layers. Use these masks to make jpegs of the device shot combined with screenshots for specific case studies.

### Specific Image suggestions for this Case Study
[ ] Full width Header Image
[ ] Image from website of clients they serve
[ ] Donation page screencap? 
[ ] Image of site speed in case study doc (linked above)

**Comment by brittstetson** [comment]
@natanialeclerc  let use these tickets to track polish as well. Can you please comment here when the draft linked above is final?

Then, when @sarahvleigh is done with images this full ticket can go to Joe for build.

**Comment by brittstetson** [comment]
Lowest priority given that content is blocked by client

**Comment by brittstetson** [comment]
@natanialeclerc are we still awaiting content approval on this one?

**Comment by natanialeclerc** [comment]
Yes @brittstetson - unfortunately probably won't get approval till next week

**Comment by brittstetson** [comment]
@natanialeclerc sounds good. We'll keep this at the bottom of the pile and make it lowest priority for images. Luckily plenty of other case studies in the mix!

**Comment by brittstetson** [comment]
@komejo we won't have FEAM ready for NTC. Can you unpublish?

**Comment by komejo** [comment]
Nothing to unpublish, has not been built!
