### ISSUE TITLE
TROR Case Study

### ISSUE THREAD

**Issue by natanialeclerc** [thinkshout/thinkshout#734]
### Overview
Images & case study for TROR Case Study on new site

Large images should crop to: min-width: 1216px. Height can vary, currently 752px.
Small images should crop to: 592 x 330
Full width images should crop to: 2000 x 900

### Links
Case Study: https://docs.google.com/document/d/1QatUzSYTKFsemkNllaRQqEEGK4g_VKrek0VasbmoRto/edit?usp=sharing

### Assets
An image library has been started that should work for at least the first few case studies.
https://drive.google.com/drive/folders/1m2FSW_J35q2HspAxfRdE8Aq1ILhUGwa8?usp=drive_open

In this folder you fill find images categorized by device type that have masks in them as layers. Use these masks to make jpegs of the device shot combined with screenshots for specific case studies.

### Specific Image suggestions for this Case Study
[ ] Header image  (full width)
[ ] Site images at various screen sizes (large)
[ ] Home page at different times of day (2 small + 1 large
[ ] image from site (full width)

**Comment by brittstetson** [comment]
@sarahvleigh: Note that the content is finished, linked above. When images are ready, this can be assigned to Joe.

**Comment by sarahvleigh** [comment]
Images ready for review via Google Doc @brittstetson

**Comment by natanialeclerc** [comment]
@vickibrown @brittstetson these look good to me - if no changes from y'all I say it's ready for Joe

**Comment by vickibrown** [comment]
@natanialeclerc @brittstetson I've asked @sarahvleigh to make some changes on this, so hold tight until you hear more.

**Comment by sarahvleigh** [comment]
@komejo ready for you

**Comment by komejo** [comment]
Ready for review: https://ntc2019--thinkshout.netlify.com/work/travel-oregon/

**Comment by natanialeclerc** [comment]
Lookin good!! @ThomasKing what do you think of the 2 text blocks back to back? the spacing there feels odd to me...

**Comment by ThomasKing** [comment]
Awesome! A few QA items:

* Stack the results content
* Intro paragraph, change "tourism marketing organization" to "destination marketing organization"
* Move the first image (desktop in outdoor setting) to the slot between the next two text blocks
* Quotation, small edits for clarity: “Your commitment to bringing a project like this to fruition is  incredible. Thank you for what your work means to all of us as tourism nerds in Oregon. Thank you!”


Thanks, Joe!!!

**Comment by komejo** [comment]
Done: https://ntc2019--thinkshout.netlify.com/work/travel-oregon/

**Comment by brittstetson** [comment]
@ThomasKing can we call this done?

**Comment by ThomasKing** [comment]
Done!
