### ISSUE TITLE
Careers

### ISSUE THREAD

**Issue by BrittSzynal** [thinkshout/thinkshout#739]
## Overview

The careers block on https://ntc2019--thinkshout.netlify.com/team/ should link to the careers page with updated content found here: https://docs.google.com/document/d/1rjP015vLpNEvWD5xN73kqZ2KSzukt6qWvSGqNmBqz4c/edit

**Comment by komejo** [comment]
https://ntc2019--thinkshout.netlify.com/careers/

**Comment by ThomasKing** [comment]
Signed off!

**Comment by levelos** [comment]
Should we remove the /team page and link to about?

**Comment by levelos** [comment]
Team, still have a couple question here.

First, the /team page is still active, but there's no way to access. Should it be removed with a redirect added to /about.

Second, I do think we need a link from /about to /careers.
