### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by BrittSzynal** [thinkshout/thinkshout#740]
## Overview

New content for https://thinkshout.com/contact/ is here: https://docs.google.com/document/d/1d8JMt9ULeiw3LpvcXYtZ8JCaTIbjZoZzQTa_0eQHKss/edit

**Comment by komejo** [comment]
Need to get with Lev re: form changes - if it's feasible to merge the first and last name fields, and add an 'organization' field.

**Comment by komejo** [comment]
https://ntc2019--thinkshout.netlify.com/contact/

**Comment by chelseamaricle** [comment]
@komejo Thomas and I would love to fill up the big orange empty space on the left a bit more. Would you mind adding this new copy?

*Our clients are making the world a better place across issues and industries.*

We support incredible work in social justice, education, environment, health and wellness, human rights, animal welfare, arts and culture, destination management, philanthropy, and technology.

*Reach out by phone or email*

503-847-9216
hello@thinkshout.com

(Note on the phone number and email address there are no labels - in other words please remove the "Phone:" and "Email:" that currently display.

**Comment by komejo** [comment]
Done: https://ntc2019--thinkshout.netlify.com/contact/

**Comment by chelseamaricle** [comment]
Thanks @komejo! It definitely looks more filled out, which is great. My bad though - somehow what I thought was bolded ended up italicized in my comment above. I'm not sure what happened there, but can we bold these 2 lines?

Our clients are making the world a better place across issues and industries.

Reach out by phone or email

**Comment by komejo** [comment]
Fixed!
