### ISSUE TITLE
SPLC Case Study

### ISSUE THREAD

**Issue by BrittSzynal** [thinkshout/thinkshout#741]
### Overview
Images & content for SPLC Case Study on new site

Large images should crop to: min-width: 1216px. Height can vary, currently 752px.
Small images should crop to: 592 x 330
Full width images should crop to: 2000 x 900

### Links
Case Study: ...add link ...

### Assets
An image library has been started that should work for at least the first few case studies.
https://drive.google.com/drive/folders/1m2FSW_J35q2HspAxfRdE8Aq1ILhUGwa8?usp=drive_open

In this folder you fill find images categorized by device type that have masks in them as layers. Use these masks to make jpegs of the device shot combined with screenshots for specific case studies.

### Specific Image suggestions for this Case Study

- [ ] Suggestions are highlighted in yellow and with a comment in the draft doc. Includes:
- [ ] Header image from original case study (full width)
- [ ] Images that reflect our deliverables: user research, persona development, landscape analysis, platform recommendations

**Comment by brittstetson** [comment]
@ThomasKing to adapt current case study to new format. Please provide a link to your Google Doc

@vickibrown to do images...flag Thomas if you need further direction

**Comment by natanialeclerc** [comment]
@ThomasKing here it is ready for your review: https://docs.google.com/document/d/17e1_WizfK-clFQi9o_w7OijTcu0OtG0tJn7Epa8AoHM/edit?usp=sharing

**Comment by ThomasKing** [comment]
@vickibrown @sarahvleigh to you for design! I updated the hate map paragraph minimally. @levelos will you review that and let us know how we should proceed with client approval? Will also ping you in our thread on Slack.

**Comment by vickibrown** [comment]
@ThomasKing @brittstetson I put together some images that should work for this, but am waiting to put them in the doc until the client signs off. We also still need a hero image approval from @mshaver 
The images can be viewed here https://drive.google.com/drive/folders/1xTdRx9mRDOv-815prDteM2sAFSDCy2-_

**Comment by brittstetson** [comment]
Design images to stage: https://drive.google.com/drive/folders/1xTdRx9mRDOv-815prDteM2sAFSDCy2-_

Waiting on client approval to go live
