### ISSUE TITLE
CLC Case Study

### ISSUE THREAD

**Issue by natanialeclerc** [thinkshout/thinkshout#742]
### Overview
Images for CLC Case Study on new site

Large images should crop to: min-width: 1216px. Height can vary, currently 752px.
Small images should crop to: 592 x 330
Full width images should crop to: 2000 x 900

### Links
Case Study Draft: https://docs.google.com/document/d/1KR22ENfeDg1LXGXsXKLiHzUlKhYfSrYbkKVkE9xdxs0/edit?usp=sharing 

### Assets
An image library has been started that should work for at least the first few case studies.
https://drive.google.com/drive/folders/1m2FSW_J35q2HspAxfRdE8Aq1ILhUGwa8?usp=drive_open

In this folder you fill find images categorized by device type that have masks in them as layers. Use these masks to make jpegs of the device shot combined with screenshots for specific case studies.

### Specific Image suggestions for this Case Study
- [ ] Header image (full width)
- [ ] images at various screen sizes (1 large image)
- [ ] Full width image from site
- [ ] Focal point module image? Or another way to demonstrate this?
- [ ] various photos from site (2 small one large)

**Comment by natanialeclerc** [comment]
@ThomasKing @brittstetson this draft is ready for review - https://docs.google.com/document/d/1KR22ENfeDg1LXGXsXKLiHzUlKhYfSrYbkKVkE9xdxs0/edit?usp=sharing 

hitting FHAO next...

**Comment by ThomasKing** [comment]
Copy approved pending a few comments. @natanialeclerc please check those and then send along for image updates.

**Comment by natanialeclerc** [comment]
Thanks! @sarahvleigh @brittstetson this one is ready for image magic!!

**Comment by sarahvleigh** [comment]
to @vickibrown for review

**Comment by vickibrown** [comment]
@sarahvleigh I think these images do a great job telling the story. @natanialeclerc would love to work with you on flipping some of the content to match.

**Comment by brittstetson** [comment]
Taking the dev tag off and adding content tag to indicate this isn't quite ready for Joe

**Comment by brittstetson** [comment]
@natanialeclerc did updates here get made?

**Comment by ThomasKing** [comment]
Closed!

**Comment by vickibrown** [comment]
@komejo it looks like we're missing a bunch of images that @sarahvleigh put together for this. Can you please add them in from the doc? https://docs.google.com/document/d/1KR22ENfeDg1LXGXsXKLiHzUlKhYfSrYbkKVkE9xdxs0/edit

**Comment by natanialeclerc** [comment]
I think some of the content still needs to be flipped too - re-sharing the updated doc just in case! https://docs.google.com/document/d/1KR22ENfeDg1LXGXsXKLiHzUlKhYfSrYbkKVkE9xdxs0/edit?usp=sharing

**Comment by komejo** [comment]
Ready for review: https://ntc2019--thinkshout.netlify.com/work/campaign-legal-center/
