### ISSUE TITLE
FHAO Case Study

### ISSUE THREAD

**Issue by natanialeclerc** [thinkshout/thinkshout#743]
### Overview
Images for FHAO Case Study on new site

Large images should crop to: min-width: 1216px. Height can vary, currently 752px.
Small images should crop to: 592 x 330
Full width images should crop to: 2000 x 900

### Links
Case Study Draft: https://docs.google.com/document/d/1HAbeGGZ7S3-k7HiWl06GIw29b8j5-VKsDL6AQ8jPPz0/edit?usp=sharing 

### Assets
An image library has been started that should work for at least the first few case studies.
https://drive.google.com/drive/folders/1m2FSW_J35q2HspAxfRdE8Aq1ILhUGwa8?usp=drive_open

In this folder you fill find images categorized by device type that have masks in them as layers. Use these masks to make jpegs of the device shot combined with screenshots for specific case studies.

### Specific Image suggestions for this Case Study
- [ ] Header image (full width)
- [ ] images at various screen sizes (1 large image)
- [ ] Full width image from site
- [ ] Focal point module image? Or another way to demonstrate this?
- [ ] various photos from site (2 small one large)

**Comment by natanialeclerc** [comment]
@brittstetson @ThomasKing I've done a quick and dirty draft of this (FHAO doesn't have a ton of content in the case study, as it is) - I'll review in the morning with fresh eyes but if you're so inclined, here it is: https://docs.google.com/document/d/1HAbeGGZ7S3-k7HiWl06GIw29b8j5-VKsDL6AQ8jPPz0/edit?usp=sharing

**Comment by ThomasKing** [comment]
@natanialeclerc back to you for closing comments, then to the images!

**Comment by natanialeclerc** [comment]
Got it! @sarahvleigh @brittstetson all done with edits - ready for images!

**Comment by sarahvleigh** [comment]
to @vickibrown for review

**Comment by vickibrown** [comment]
@sarahvleigh comments are in.

**Comment by sarahvleigh** [comment]
@komejo this is ready for you.

**Comment by vickibrown** [comment]
@komejo I made a few edits to the image layouts here. There's now just 3 large images you can reference placement here https://docs.google.com/document/d/1HAbeGGZ7S3-k7HiWl06GIw29b8j5-VKsDL6AQ8jPPz0/edit#
Thanks!

**Comment by komejo** [comment]
Ready for review: https://ntc2019--thinkshout.netlify.com/work/facing-history-redesign/
