### ISSUE TITLE
Consider dropping the active color from Contact in nav

### ISSUE THREAD

**Issue by ThomasKing** [thinkshout/thinkshout#745]
@vickibrown the persistent orange Contact menu item trips me up. It looks like an active state. May we consider a different treatment for calling that out (including no special treatment at all? I'd argue that no user will have trouble finding how to contact us when they want).

This is related to a consideration for orienting users to the page/section they're in. If we drop this orange treatment, we could have that available for an active state on screens where the menu is visible.

I'd also like to consider brining in a small page title for our landing pages: Services and About, something like what's in the attached screen shot/mockup.

![Screen Shot 2019-03-06 at 4.47.19 PM.png](https://images.zenhubusercontent.com/59273cc551aa2c30577f7bcc/a85920a7-5d97-412e-b9da-5fd33d20ae81)

**Comment by brittstetson** [comment]
@ThomasKing @vickibrown are we trying to get this in for NTC?

**Comment by vickibrown** [comment]
@ThomasKing I hear you on this. We could just make it the same color and bold. @komejo can you give this a try?

**Comment by komejo** [comment]
Ready for review: https://ntc2019--thinkshout.netlify.com/

**Comment by ThomasKing** [comment]
Awesome!!!
