### ISSUE TITLE
Our Work Copy Updates

### ISSUE THREAD

**Issue by chelseamaricle** [thinkshout/thinkshout#746]
## Short description
Updates to the work section to replace the current landing page (https://thinkshout.com/work/) with the style of the work archive page (https://thinkshout.com/work/archive/) but with some edits as detailed in the attachment.

## How should this function? 
The "Work" link in the header should link directly to a page styled like this one: https://ntc2019--thinkshout.netlify.com/work/archive/  with the following copy and layout updates: https://docs.google.com/document/d/1rJ-7nkGMyV3BXSdlnvpN7gK5d4GXq_7VghzajyhCvlc/edit?usp=sharing

**Comment by brittstetson** [comment]
@ThomasKing and @vickibrown do you have feedback on this update: https://ntc2019--thinkshout.netlify.com/work/

**Comment by ThomasKing** [comment]
I'm signed off on this change from featured and archive to a single work page. Thanks!

**Comment by vickibrown** [comment]
@brittstetson @ThomasKing I'm inclined to move the orange contact bar to the bottom. Also, updating our client list as Brett mentioned would make sense.

**Comment by ThomasKing** [comment]
Agreed.
