### ISSUE TITLE
Remove case studies that aren't updated for NTC, and redirect to /work (list in comments)

### ISSUE THREAD

**Issue by ThomasKing** [thinkshout/thinkshout#747]
To remove:
* Colorado Trust
* Environmental Defense Fund
* The first FHAO (/work/facing-history/) -- note that there are two for FHAO and we're updating the more recent
*  Families USA
* Feeding Texas
* Salmon Project
* Giving Forum
* HSUS Change for Animals (redirect to HSUS if possible)
* Los Angeles Conservancy
* Lemelson
* MailChimp
* Mercy Corp
* MIUSA
* NCYL
* Ocean Outcomes
* Portland Design Works
* SPLC Selma microsite
* Intertwine Alliance
* Salmon Project
* Travel Portland
* World Wildlife Fund

Whew! We'll revisit these after NTC launch.

**Comment by komejo** [comment]
Done: https://ntc2019--thinkshout.netlify.com/work/
Redirect in action: https://ntc2019--thinkshout.netlify.com/work/coloradotrust/

**Comment by ThomasKing** [comment]
@komejo Feeding Texas snuck back in :)

It's redirecting correctly to /work, but it remains in the list.

**Comment by komejo** [comment]
There was some stray control code at the bottom(?) of this case study, it has been removed.

**Comment by brittstetson** [comment]
@ThomasKing can we call this done?

**Comment by ThomasKing** [comment]
Done!
