### ISSUE TITLE
WonderLab: QA for Landing Page

### ISSUE THREAD

**Issue by juliaford** [thinkshout/thinkshout#789]
Link: https://stage.thinkshout.com/wonderlab/

**Comment by vickibrown** [comment]
@juliaford @levelos Some tweaking below, nothing is critical but anything is nice to do.

- [ ] Remove extra padding between Curiosity | Impact | Optimism
- [ ] Remove italic styling from illustration credit
- [ ] Make Sarah's Name a link to her page on TS.com **and bold her name**
- [ ] reduce padding beneath headlines to match padding above headlines (it's about 50%)
 double padding beneath articles at the bottom of the page

Extra nice to have not critical for now:
- [ ] increase site margins on tablet and smaller by 50%

Screenshots:
![Screen Shot 2020-01-21 at 12 00 20 PM](https://user-images.githubusercontent.com/21184833/72839500-3e130580-3c47-11ea-9cb0-25986899dcdd.png)
![Screen Shot 2020-01-21 at 12 03 43 PM](https://user-images.githubusercontent.com/21184833/72839501-3e130580-3c47-11ea-9486-5a07fbd2b1a0.png)
![Screen Shot 2020-01-21 at 12 05 19 PM](https://user-images.githubusercontent.com/21184833/72839502-3e130580-3c47-11ea-862f-5dacf432fcfe.png)
![Screen Shot 2020-01-21 at 12 06 29 PM](https://user-images.githubusercontent.com/21184833/72839503-3e130580-3c47-11ea-9f49-9284b0a2843d.png)
