### ISSUE TITLE
WonderLab: QA Julia's Article 

### ISSUE THREAD

**Issue by juliaford** [thinkshout/thinkshout#790]
Link: https://stage.thinkshout.com/wonderlab/consent-based-calibration/business/

**Comment by vickibrown** [comment]
@juliaford @levelos these edits are for all detail pages.
- [ ] Double the padding above the headline
- [ ] Add an underline to body text links
![Screen Shot 2020-01-21 at 12 18 02 PM](https://user-images.githubusercontent.com/21184833/72840034-4750a200-3c48-11ea-939c-e0d2b1219eb1.png)
![Screen Shot 2020-01-21 at 12 16 36 PM](https://user-images.githubusercontent.com/21184833/72840043-4b7cbf80-3c48-11ea-92bb-897b76c945e7.png)

**Comment by juliaford** [comment]
@levelos to you, please apply to all detail pages!
