### ISSUE TITLE
WonderLab QA: Kate's Intro Page

### ISSUE THREAD

**Issue by juliaford** [thinkshout/thinkshout#791]
Link: https://stage.thinkshout.com/wonderlab/consent-based-calibration/introduction/

**Comment by vickibrown** [comment]
@juliaford @levelos on @katelesniak 's article, lets apply a style change to the section heads.
- [ ] Keep each Concept #: as an H2
- [ ] What is currently Italic, insert a line break and make it an H3

Let's see how that looks
![Screen Shot 2020-01-21 at 12 21 08 PM](https://user-images.githubusercontent.com/21184833/72840301-c940cb00-3c48-11ea-95b7-03e54d61d6a0.png)

**Comment by juliaford** [comment]
@levelos to you

**Comment by vickibrown** [comment]
@levelos can we fix the first one too?
https://stage.thinkshout.com/wonderlab/consent-based-calibration/introduction/
<img width="1014" alt="Screen Shot 2020-01-21 at 8 06 19 PM" src="https://user-images.githubusercontent.com/21184833/72864628-8eab5280-3c89-11ea-8da4-358a0fae2947.png">
