### ISSUE TITLE
Quarterly Support: Dev Must Dos

### ISSUE THREAD

**Issue by juliaford** [thinkshout/thinkshout#800]
## Quarterly Support Tasks
The goal of this ticket is for us to stay on top of monthly maintenance and regular smaller ticket tasks in line with our new support contracts that stipulate a certain % of hours to be used for routine maintenance. The Project Manager will need to specify exactly how many hours should be used here (remember to leave time for QA and pushing live). 

## Review
- [ ] Is site up to date w/ Drupal core? Or WP equivalent? 
- [ ] Are all modules/plugins updated?
- [ ] Are there any low hanging fruit (1hr or less) open tickets that are bug fixes or small UI improvements? 
- [ ] Are there errors in the logs that could be taken care of or estimated? 
- [ ] Are there other ideas for improvement you can see? 

## Update
- [ ] If there are Drupal core or WP updates to make and they can be done within the allocated time, proceed with updating. 
- [ ] If updates will take longer, estimate and assign ticket to PM to communicate. 
- [ ] If there are small fixes or issues from the error log that can be fixed within the time, proceed or estimate those. 

## QA
- [ ] QA any updates and assign to the PM

## Deploy
- [ ] Work with PM on deploy for this client

**Comment by unclegcb** [comment]
Is the contract language compatible with other routine improvements like site performance, privacy, and accessibility concerns?

**Comment by juliaford** [comment]
@unclegcb from the contract:
" Up to twenty percent (20%) of allocated hours will be dedicated to proactive, routine maintenance performed on a quarterly basis. This will include reviewing the site, completing simple module or plugin updates, and making any recommendations for more time-intensive updates (defined as 4 hours or more)."
