### ISSUE TITLE
Accessibility Statement page

### ISSUE THREAD

**Issue by JulesKhong** [thinkshout/thinkshout#809]
Create an Accessibility Statement page at /accessibility that's available from the footer as well as from a link at the top of the page that's invisible until it's focused on. (only visible on focus). 

Include an Accessibility Statement @ThomasKing 
- [Example short-form and long-form statements](https://docs.google.com/document/d/1Kyo8dZ3cqkQoG58b4-elXKIMAMRdaWfZZeLmvtD3p5w/edit?usp=sharing)
- Other considerations we need to solve for:
Who receives feedback? How quickly do we respond? How do we prioritize issues and get them into the queue? How do we circle back and close the loop for users? How often do we review our site for accessibility?
 
The feedback can be through an email address with a pre-populated subject line or a contact form.

**Comment by ThomasKing** [comment]
@JulesKhong I've made suggestions to the samples here: https://docs.google.com/document/d/1Kyo8dZ3cqkQoG58b4-elXKIMAMRdaWfZZeLmvtD3p5w/edit#

With those, I think we're good shape and will look for your replies before creating a draft for TS and getting it over to Olivia.

**Comment by ThomasKing** [comment]
@JulesKhong with the example pages done, where would you prefer me to draft ThinkShout's page?
