### ISSUE TITLE
Blog Landing Page Redesign

### ISSUE THREAD

**Issue by komejo** [thinkshout/thinkshout#859]
## Overview 
The blog landing page is stale and kinda boring, let's make it POP!

New Design: https://thinkshout.invisionapp.com/console/ThinkShout.com-ckemgpqp81dxj01wlghziko2l/ckemgqugq1eo901wlfmgcjqjs/play

## Screenshots
![Screen Shot 2020-09-29 at 12 51 15 PM](https://user-images.githubusercontent.com/1668324/94608647-8cef5100-0252-11eb-8916-8585e64d3a3f.png)

## Relevant Links
https://thinkshout.com/blog/

**Comment by komejo** [comment]
Ready for review! https://blog-redesign--thinkshout.netlify.app/blog/

**Comment by sarahvleigh** [comment]
Looking great @komejo. Thanks for working your magic here.

**Design Feedback**
- [ ] When I click on a taxonomy, that term should remain orange to let me know where I'm at. See example from designs after I click on "accessibility":

- [ ] After I've selected a specific taxonomy, I should only see a grid of posts from most recent to oldest (no need for featured posts or XL full width posts). Here's the design:
https://thinkshout.invisionapp.com/console/share/QB1JQ03KPE/429265032

- [ ] I see some broken featured images on old posts. Might want to investigate or have a fallback image if they don't have one. 

<img width="419" alt="Screen Shot 2020-09-29 at 2 37 32 PM" src="https://user-images.githubusercontent.com/31553337/94619296-7dc3cf80-0261-11eb-926c-93f86f4c3c2c.png">

- [ ] I don't see any lazy load functionality happening on the page. Are we doing that? If so, what info do you need from us to set up parameters?

- [ ] Let's reduce padding to 1/2 of the current padding on these single posts. 
<img width="409" alt="Screen Shot 2020-09-29 at 2 52 05 PM" src="https://user-images.githubusercontent.com/31553337/94621262-d6e13280-0264-11eb-8678-594400f97459.png">

**Comment by komejo** [comment]
Done and ready for review: 
https://blog-redesign--thinkshout.netlify.app/blog/

**Comment by levelos** [comment]
Text overlapping with byline in full width hero's
<img width="517" alt="image" src="https://user-images.githubusercontent.com/104897/94996423-d47f2100-0561-11eb-89ee-258d4f06fcc9.png">

Maybe move byline to the bottom right?

**Comment by levelos** [comment]
Few questions around the content strategy with this new approach: /cc @juliaford 

- [ ] Can we feature articles to be pinned to the top and/or full width?
- [ ] Should we add pagination to the topic landing pages? Some, E.g., Tech, are really long.
- [ ] Do we plan resuming posting Spark to the blog? If not, do we need that Topic? I think trimming to 5 would be more balanced.
- [ ] Do the existing _Home_ and _Featured_ attributes on blog posts have an impact?
- [ ] Do we need to reclassify older blog posts, or do they slot in to the new Topics?

**Comment by juliaford** [comment]
@levelos Spark is going away- that topic will be deleted @komejo and flagging that Olivia has a migration/re-tagging document all done that she will need to collaborate with you on in terms of classifying old posts cc: @ooldach

**Comment by komejo** [comment]
Latest is up and ready for review: https://blog-redesign--thinkshout.netlify.app/blog/

Note: the only thing not implemented here was the pagination for topic pages, because you can't do that by default in Jekyll! You can only pick one 'page' of posts to paginate. There's a https://github.com/midnightSuyama/jekyll-paginate-category plugin, but before I implemented it, I was wondering if the post-trimming might solve the issue? 

Also, the post-trimming doc referred to a 'U/X & Design' category, so I added it. Is it needed?
